KCI-136 > build and lint (and package.json lint)
kingscode/vue-cli-plugin-kingscode-scaffold pull request #28
Opened 2020-12-07 15:03 UTC by jvhellemondt

2020-12-07 15:10 UTC, ricardovanlaarhoven commented
Yes you can!

run `vue create test-scaffold`
and `vue add vuetify`

and then `npm i path\to\scaffold`
followed by `vue invoke kingscode-scaffold`

2020-12-07 15:15 UTC, ricardovanlaarhoven requested changes
wouldn't it be cool if this was configured using a checkbox in the prompts? (just like fontawesome)

Then we can remove that run lint from the readme as well and can people choose that themselves

2020-12-07 15:15 UTC, ricardovanlaarhoven commented on README.md
> +  > eslint-config-airbnb
do we? `eslint-config-airbnb`

2020-12-07 15:15 UTC, ricardovanlaarhoven commented on generator/templates/Deployment/_github/workflows/build_and_lint.yml
> +          echo "//npm.fontawesome.com/:_authToken=$FONT_AWESOME_TOKEN" >> .npmrc
Here should be an if

2020-12-07 15:15 UTC, ricardovanlaarhoven commented on generator/templates/Deployment/_github/workflows/deploy.demo.yml
> -      - 'env/production'
don't change that. Production is the default, not all projects have a demo env
(and also the file name)

2020-12-07 15:15 UTC, ricardovanlaarhoven commented on generator/templates/Deployment/_github/workflows/deploy.demo.yml
> -      - 'env/production'
But al projects have a production :D

2020-12-09 07:00 UTC, ricardovanlaarhoven approved these changes

2020-12-09 07:04 UTC, jvhellemondt commented
> Ricardo
>> beside my comments:
>> wouldn't it be cool if this was configured using a checkbox in the prompts? (just like fontawesome)
>> 
>> Then we can remove that run lint from the readme as well and can people choose that themselves

The `run lint` is in the default Vue README, I'd suggest to keep it (the default README) in favor of future updates on it. However, the checkbox is a very good idea.

2020-12-09 08:42 UTC, ricardovanlaarhoven approved these changes

2020-12-09 11:11 UTC, merged