KCI-141 Always redirect user to loginpage with success-message
kingscode/vue-cli-plugin-kingscode-scaffold pull request #30
Opened 2020-12-22 08:53 UTC by martn001

2020-12-22 09:11 UTC, martn001 commented on generator/templates/Authorisation/src/views/authorisation/RegistrationVerify.vue
> +            this.$router.push({name: 'login', query: {message: 'registrationVerify'}});
I thought there also should be a redirection after when registration has been verified.

2020-12-22 10:01 UTC, jvhellemondt approved these changes
Akkoord zolang de gebruiker wel duidelijk kan zien dat zijn registratie gelukt is.

2020-12-23 06:59 UTC, ricardovanlaarhoven requested changes

2020-12-23 06:59 UTC, ricardovanlaarhoven commented on generator/templates/Authorisation/src/locales/nl/authorisation.json
> +        }
You forgot to remove these messages below (i quess where you copied them from?)
for example line 23

2020-12-23 07:00 UTC, merged

2020-12-23 07:07 UTC, ricardovanlaarhoven commented on generator/templates/Authorisation/src/locales/nl/authorisation.json
> +        }
Really weird, when opening this branch local they were removed..